---
- name: OCP | ServiceMeshMemberRolls Role | Log in (obtain access token)
  k8s_auth:
    username: "{{ ocp_username }}"
    password: "{{ ocp_password }}"
    host: "{{ api_url }}"
    verify_ssl: "{{ ocp_verify_ssl }}"
  register: k8s_auth_results
  when: (ocp_token is not defined or ocp_token == "")

- name: OCP | ServiceMeshMemberRolls | Set the OCP API token value and rescue_retries control variable
  set_fact:  
    token: "{% if ocp_token is defined and ocp_token != '' %}{{ ocp_token }} {% else %}{{ k8s_auth_results.k8s_auth.api_key }}{% endif %}"
    rescue_retries: 0
  no_log: true

- name: OCP | ServiceMeshMemberRolls | Try update SMMR until success
  include_tasks: update_smmr.yml

- name: OCP | ServiceMeshMemberRolls Role | Log out (revoke access token)
  k8s_auth:
    state: absent
    api_key: "{{ token }}"
    host: "{{ api_url }}"
    verify_ssl: "{{ ocp_verify_ssl }}"
  when: k8s_auth_results.k8s_auth.api_key is defined
