---
- name: OCP | ServiceMeshMemberRolls | Set the OCP API token value and rescue_retries control variable
  set_fact:  
    token: "{{ servicemesh_creation_sa }}"
    rescue_retries: 0
  no_log: true

- name: OCP | ServiceMeshMemberRolls | Try update SMMR until success
  include_tasks: update_smmr.yml
