apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-upgrade-sa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-upgrade-sa
rules:
  - verbs:
      - get
      - list
      - update
      - patch
    apiGroups:
      - '*'
      - 'operators.coreos.com'
      - 'installplans.operators.coreos.com'
    resources:
      - installplans
  - verbs:
      - get
      - list
    apiGroups:
      - '*'
    resources:
      - subscriptions
  - verbs:
      - get
      - list
    apiGroups:
      - 'project.openshift.io'
      - ''
    resources:
      - namespaces
      - projects
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-upgrade-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-upgrade-sa
subjects:
  - kind: ServiceAccount
    name: operator-upgrade-sa
    namespace: default
