---
- name: Install Redis Cluster
  hosts: target1,target2,target3
  tasks:
   -  include_vars:
        dir: roles/redis_install/vars
        extensions:
          - yml
   - import_role:
        name: redis_install
   - import_role:
        name: stunnel
     when: stunnel_install
- import_playbook: roles/redis_install/tasks/cluster.yml
