#copy Kibana rpm file
- name: copy kibana rpm
  copy:
    src: "{{ kibana_rpm }}"
    dest: "{{ kibana_rpm }}"
  when: ansible_hostname == "{{ node_name1 }}"

  #install Kibana on Nexus
- name: install kibana
  yum:
    name: "{{ kibana_rpm }}"
    state: present
  when: ansible_hostname == "{{ node_name1 }}"

  #Deploy Kibana template
- name: Deploy Kibana File
  template: src="{{ kibana_jinja_template }}" dest="{{ kibana_path_dir }}"
  notify:
      restart kibana
  when: ansible_hostname == "{{ node_name1 }}"
