- name: Check Azure Advisor Recommendation
  hosts: jumpserver  # Run the task on the Ansible control node
  gather_facts: no  # We don't need facts for this task
  vars_files:
    - vault.yaml
  tasks:
    - name: Clone Private Git Repo
      git:
        repo: "https://oauth2:{{ svc_token }}@amygitaddrese.com/repos/Script.git"
        dest: "/opt/repos"
        update: yes
        force: yes
        clone: yes
      no_log: true
    
    - name: Set Executable Mode for resources.sh
      become: true
      file:
        path: "/opt/repos/Azure_Advisor_Recommendation/azure_advisor_recommendation_reports.sh"
        mode: "a+x"

    - name: Run Automation Code
      shell: "/opt/repos/Azure_Advisor_Recommendation/azure_advisor_recommendation_reports.sh"
      environment:
         username : "{{ username }}"
         password : "{{  password }}"
         tenant : "{{ tenant }}"
      no_log: true
