- name: OCP | Project | Check Permissions ark test environment
  hosts: dev
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml

- name: OCP | Project | Check Permissions ark prod environment
  hosts: prod
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml

- name: OCP | Project | Check Permissions hosting test environment
  hosts: hosting-test
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml    

- name: OCP | Project | Check Permissions hosting prod environment
  hosts: hosting-prod
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml

- name: OCP | Project | Check Permissions lab environment
  hosts: lab
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
