#stunnel Variable
Requires: "stunnel.service"

#Redis Files Driectory
stunnel_rpm: stunnel-5.41-1.el7.x86_64.rpm

#stunnel directories
stunnel_dir: "/etc/stunnel"
stunnel_cert_dir: "/etc/stunnel/certificates"
stunnel_conf_path: "/etc/stunnel/stunnel.conf"
stunnel_service_path: /usr/lib/systemd/system/stunnel.service

#Certificate for Stunnel
#create cert file URL: https://support.microfocus.com/kb/doc.php?id=7013103
cert: "/etc/stunnel/certificates/"
#cert_name: "example.pem"
cert_name: "redis-server.crt"
key_name: "redis-server.key"

cert1: "{{ cert}}{{cert_name}}"
cert2: "{{ cert}}{{key_name}}"

pid:  "/var/run/stunnel.pid"
log: "/var/log/stunnel.log"

#SSL configuration for Stunnel
fips: "no"
sslVersion: "all"
SSLv2: "NO_SSLv2"
SSLv3: "NO_SSLv3"
TLSv1: "NO_TLSv1"

#Stunnel Templates
stunnel_jinja_conf: "stunnel.conf.j2"
stunnel_jinja_service: "stunnel.service.j2"

#Enviroment Stunnel Service
LimitNOFILE: 300000
TimeoutSec: 600
