- name: OCP | Project | delete user
  hosts: dev
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "ocp-cluster1"

- name: OCP | Project | delete user
  hosts: prod
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "ocp-cluster1"

- name: OCP | Project | delete user
  hosts: cluster2-test
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "ocp-cluster2"

- name: OCP | Project | delete user
  hosts: cluster2-prod
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "ocp-cluster2"

- name: OCP | Project | delete user
  hosts: cluster3-test
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "ocp-cluster3"    

- name: OCP | Project | delete user
  hosts: cluster3-prod
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "ocp-cluster3"

- name: OCP | Project | delete user
  hosts: lab
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "lab"
