- name: OCP | Project | quota update/get for DEV environment
  hosts: dev
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: update_quota_test.yaml

- name: OCP | Project | quota update/get for TEST environment
  hosts: test
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: update_quota_test.yaml

- name: OCP | Project | quota update/get for QA environment
  hosts: qa
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: update_quota_prod.yaml

- name: OCP | Project | quota update/get for PROD environment
  hosts: prod
  gather_facts: no
  serial: 1
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: update_quota_prod.yaml
