apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-project-sa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delete-project-sa
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - deploymentconfigs
      - deployments
      - namespaces
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - hostsubnets
      - netnamespaces
  - verbs:
      - delete
    apiGroups:
      - 'project.openshift.io'
    resources:
      - namespaces
      - projects
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-project-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: delete-project-sa
subjects:
  - kind: ServiceAccount
    name: delete-project-sa
    namespace: default
