galaxy_info:
  author: Oktay Savdi
  description: Apache Kafka installation
  company: your company (optional)
  license: license
  min_ansible_version: 2.8.5
  galaxy_tags: [Apache,Kafka,MQ]
dependencies: []
