---
# Task for set API token (obtained in previous task or passed as parameter, ie a Service Account token)
- name: OCP | Limits | Set the OCP API token value
  set_fact:  
    token: "{{ limitrange_creation_sa }}"
  #no_log: true

# Task for set Resource Limits to project
- name: OCP | Limits Role | Set Project Limits
  k8s:
    api_key: "{{ token }}"
    host: "{{ api_url }}"
    verify_ssl: "{{ ocp_verify_ssl }}"
    state: present
    definition: "{{ lookup('template', 'limit.yml.j2') | from_yaml }}"
    force: true
    validate:
      fail_on_error: no
      strict: yes
  loop:
    "{{ limit_ranges }}"

# Task for set Resource Limits to project
- name: OCP | Limits Role | Check Project Limits
  k8s_facts:
    api_version: v1
    api_key: "{{ token }}"
    host: "{{ api_url }}"
    verify_ssl: "{{ ocp_verify_ssl }}"
    kind: LimitRange
    namespace: "{{ project_name }}"
  register: get_limits

# Tag to show results
- debug:
    var: get_limits.resources
