- name: Check disk public access status
  hosts: jumpserver  # Run the task on the Ansible control node
  gather_facts: no  # We don't need facts for this task
  vars_files:
    - vault.yaml
  tasks:
    - name: Save disk public access status to a file
      shell: /opt/HCE/HCE_Azure_Resources_utilization/resources_utilization.sh
    
    - name: Read the contents of Azure_Resources_Utilization.txt
      slurp:
        src: "/opt/HCE/HCE_Azure_Resources_utilization/Azure_Resources_Utilization.txt"  # Replace with the actual path to your Azure_Resources_Utilization.txt file
      register: file_content

    - name: Check file contains 
      set_fact:
        lines_found: "{{ file_content.content | b64decode | split('\n') }}"
    
    - name: Send Email with Azure Resource Utilization
      become: false
      mail:
        host: myhost.mydomain.com
        port: 25
        sender: ansible@mydomain.com
        to: myteam@mydomain.com
        subject: "[ Warning ] Azure Resource Utilization Report"
        attach: "/opt/HCE/HCE_Azure_Resources_utilization/Azure_Resources_Utilization.txt"
        body: |
            Azure Resource Utilization Report [ Monthly ]
    
            Please check the list and Report the Service Owner!!
      when: lines_found

    - name: delete result file
      shell: rm -rf "/opt/HCE/HCE_Azure_Resources_utilization/Azure_Resources_Utilization.txt"

