apiVersion: v1
kind: ServiceAccount
metadata:
  name: perms-sa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: perms-sa
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - rbac.authorization.k8s.io
      - authorization.openshift.io
    resources:
      - rolebindings
      - roles
  - verbs:
      - get
      - list
      - watch
      - update
      - create
    apiGroups:
      - user.openshift.io
    resources:
      - groups
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: perms-sa1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: perms-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: perms-sa2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: perms-sa
subjects:
  - kind: ServiceAccount
    name: perms-sa
    namespace: default
