- name: OCP | Project | Launch playbook for environment
  hosts: "{{ namespace.split('-')[-1] }}"
  gather_facts: no
  serial: 1
  vars:
    namespace: oktay-dev
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "ocp-cluster1"

- name: OCP | Project | Launch playbook for environment
  hosts: "hosting-{{ namespace.split('-')[-1] }}"
  gather_facts: no
  serial: 1
  vars:
    namespace: oktay-dev
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "ocp-cluster2"
        
- name: OCP | Project | Launch playbook for environment
  hosts: "{{ namespace.split('-')[-1] }}"
  gather_facts: no
  serial: 1
  vars:
    namespace: oktay-dev
  tasks:
    - name: OCP | Project | Launch playbook for environment
      import_tasks: all.yaml
      when: cluster == "lab"
