- name: ocp check namespace exist
  shell: |
    curl -ks -H "Authorization: Bearer {{ sa_token }}" -H 'Accept: application/json' "{{ url }}/api/v1/namespaces" --insecure | jq -r '.items[].metadata.name' | grep -xc "{{ namespace }}-{{ env }}" || true
  register: check_namespace_exist

- name: "Namespace does not exist - [{{ namespace }}-{{ env }}]"
  debug:
    msg: "Namespace does not exist - [{{ namespace }}-{{ env }}]"
  when: check_namespace_exist.stdout != "1"

- meta: end_play
  when: check_namespace_exist.stdout != "1"

- name: ocp check pv exist
  shell: |
    curl -ks -H "Authorization: Bearer {{ sa_token }}" -H 'Accept: application/json' "{{ url }}/api/v1/persistentvolumes" --insecure | jq -r '.items[].metadata.name' | grep -xc "{{ namespace }}-{{ env }}-batch-pv" || true
  register: check_pv_exist

- name: "the pv is exist"
  debug:
    msg: "the pv is exist"
  when: check_pv_exist.stdout == "1"

- meta: end_play
  when: check_pv_exist.stdout == "1"

- name: mount /mnt/nfs
  raw: mount {{ storage }} /mnt
  ignore_errors: true

- name: Creates {{ namespace }} and {{ namespace }}-{{ env }}
  file:
    path: "/mnt/{{ item }}"
    state: directory
    mode: '0777'
    force: yes
    recurse: yes
  with_items:
    - "{{ namespace }}"
    - "{{ namespace }}/{{ namespace }}-{{ env }}/data01"

- name: ocp create pv
  shell: |
    curl -k \
        -X POST \
        -d @- \
        -H "Authorization: Bearer {{ sa_token }}" \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        {{ url }}/api/v1/persistentvolumes/ <<'EOF'
    {
      "apiVersion": "v1",
      "kind": "PersistentVolume",
      "metadata": {
        "name": "batch-{{ namespace }}-{{ env }}-pv"
       },
       "spec": {
        "accessModes": [
          "ReadWriteMany"
        ],
        "capacity": {
          "storage": "5Gi"
        },
        "claimRef": {
          "apiVersion": "v1",
          "kind": "PersistentVolumeClaim",
          "name": "batch-{{ namespace }}-{{ env }}-pvc",
          "namespace": "{{ namespace }}-{{ env }}"
        },
        "nfs": {
          "path": "/{{ storage_path }}/{{ namespace }}/{{ namespace }}-{{ env }}/data01",
          "server": "{{ server }}"
        },
        "persistentVolumeReclaimPolicy": "Recycle"
      }
    }
    EOF
  args:
    executable: /bin/bash

- name: umount /mnt/nfs
  raw: umount -f /mnt && umount -f /var/mnt
  ignore_errors: true
