---
- name: OCP | Project | Set the OCP API token value
  set_fact:  
    token: "{{ ns_creation_sa }}"
    project_exists: false
  no_log: true

- name: OCP | Project | Get projects facts
  k8s_facts:
    api_version: v1
    api_key: "{{ token }}"
    host: "{{ api_url }}"
    verify_ssl: "{{ ocp_verify_ssl }}"
    kind: Namespace
    namespace: "{{ project_name }}"
  register: get_projects

- name: OCP | Project | Check if project exists
  set_fact:
    project_exists: true
  loop: "{{ get_projects.resources }}"
  when: "project_name == item.metadata.name"

- name: OCP | Project Role | Create project
  include_tasks: create_tasks.yml
  when: (not project_exists and project_action == "create")

- name: OCP | Project | Delete project
  include_tasks: delete_tasks.yml
  when: (project_exists and project_action == "delete")
