- name: Disk Public Access Action
  hosts: jumpserver  # Run the task on the Ansible control node
  gather_facts: no  # We don't need facts for this task
  vars_files:
    - vault.yaml
  tasks:
    - name: Clone Private Git Repo
      git:
        repo: "https://oauth2:{{ svc_token }}@mygitaddres.com/repos/Script.git"
        dest: "/opt/repos"
        update: yes
        force: yes
        clone: yes
      no_log: true
    
    - name: Set Executable Mode for script
      become: true
      file:
        path: "/opt/repos/Disable_Azure_Disk_Public_Access/disk_access_changes.sh"
        mode: "a+x"

    - name: Run AKS Deprecated Automation
      shell: "/opt/repos/Disable_Azure_Disk_Public_Access/disk_access_changes.sh"
      environment:
        username : "{{ username }}"
        password : "{{  password }}"
        tenant : "{{ tenant }}"
      no_log: true
    
    - name: Read the contents of disk_access_changes.log
      slurp:
        src: "/opt/repos/Disable_Azure_Disk_Public_Access/disk_access_changes.log"
      register: file_content

    - name: Check file contains 
      set_fact:
        contains_enabled: "{{ 'INFO' in file_content.content | b64decode | string }}"
    
    - name: Sending an e-mail SMTP servers
      become: false
      mail:
        host: myhost.mydomain.com
        port: 25
        sender: ansible@mydomain.com
        to: myteam@mydomain.com
        subject: "[ INFO ] Public Disk Access is closed"
        attach: /opt/repos/Disable_Azure_Disk_Public_Access/disk_access_changes.log
        body: |
            Public Access Enabled Disks Action Report [ Daily ]
      when: contains_enabled

    - name: delete result file
      shell: rm -rf "/opt/repos/Disable_Azure_Disk_Public_Access/disk_access_changes.log"
