apiVersion: v1
kind: ServiceAccount
metadata:
  name: egress-creation-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egress-creation-sa
rules:
- apiGroups:
  - network.openshift.io
  - ""
  resources:
  - hostsubnets
  - netnamespaces
  verbs:
  - get
  - list
  - create
  - patch
- apiGroups:
  - project.openshift.io
  - ""
  resources:
  - namespaces
  - projects
  verbs:
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: egress-creation-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: egress-creation-sa
subjects:
- kind: ServiceAccount
  name: egress-creation-sa
  namespace: default
