---
- include_tasks: memory_dump.yml
  when: choose == "memory"

- include_tasks: cpu_dump.yml
  when: choose == "cpu"

- include_tasks: gc_collect.yml
  when: choose == "gc"

- include_tasks: top_result.yml
  when: choose == "top"
