- name: "OpenShift CLI login"
  shell: oc login --token {{ token_ocpcluster1 }} --insecure-skip-tls-verify=false
  when: cluster == "ocpcluster1"

- name: "OpenShift CLI login"
  shell: oc login --token {{ token_ocpcluster2 }} --insecure-skip-tls-verify=false
  when: cluster == "ocpcluster2"

- name: "OpenShift CLI login"
  shell: oc login --token {{ token_ocpcluster3 }} --insecure-skip-tls-verify=false
  when: cluster == "ocpcluster3"
  
- name: "Get dump for top"
  shell: oc exec {{ pod_name }} -c "$(echo {{ pod_name }} | rev | cut -d "-" -f3- | rev)" -n "$(oc get po --all-namespaces | grep -i {{ pod_name }} | awk '{print $1}')" -- top -b -n 1 -H -p 1 > /tmp/{{ pod_name }}-top.out

- name: "copy dump file to ftp"
  shell: curl -T /tmp/{{ pod_name }}-top.out ftp://{{ftp_server}}/{{ftp_path}}/{{ pod_name }}-top.out && rm -rf /tmp/{{ pod_name }}-top.out
